sudo: false
language: node_js
node_js:
- '4.2'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update -g npm
after_success:
- npm run deploy
env:
  global:
  - secure: rIBbFplmoWEm1gQJEJgS+0fK5OFS5ETwEMPyakahNWOpx+ZH8UBWBw7xFnyjaIWlZzl0cFo4C4TLsEekP92Tw01L/fEVbImPwviimh7DpWX/fQ66ADdM89lCzcU4cl7Z4u+kQf5jAXUl0QQCc/hQEv2UaCpMm+8hX/Z153diYjXVAskR69dMtrywbHJJT+HDTstAp73piZYEHRsJrOoGJSFqRbx4Y9eMNwG5OZTIBoqxuRZ03Y5zkfVtBpdM7ixYzNlGOH0CZtgQtV5dvUcXSznUK9bTvAtt6gMvFNAr+JVfzYjYpe4a7hkcjBODWOg73NYJnGUGQwbbJ0ZAxDya64PoHFGOGorxP0cLXHRQmJOnlwfKEtYx7zzeIKt8kUd/RZw4PUX55tIyUHCX5Yb7p1ewmECy8idBJpeGaUQqnXVSRVSgnSWHgSCOlxhJJp58jo0qyxRN1ZhlkBsf088JulsCX1sSov3Iu9O1zHS2ROhi0i+tuilKFQ1fZ4z2bn8jpDwFbr9LZO4LQ3BBX67zqiGRv+d2P8tqsNMQDJD46Z7asF8q2r10dT3muxMsox/5rI88NIfw7ZelUQxCVUZLXCK3hNWgolwDfaM7sU99bVkrzAcr+8OPAWPeAP7h6oSVGwJLw8ABoyfkxrNyE7o4tdZhKOJhhlbpZfTiOMRI0rk=
