sudo: false
language: node_js
node_js:
- '4.2'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update -g npm
after_success:
- npm run deploy
env:
  global:
  - secure: jhDZC/I/D8msTHanogW9qAYim5A07huCY+USYsgIO2UE2f+8LSGomNnFJumNJQEOBAXmtikL3RP4puZGqfQXuhuxDz1al1hwzgS6mLvvuVXxuNxEIRBVbxHBjvNFhfOow1xG+hQw/Pj92UYczCajB1lEus5AbJrjoNlB/ltzgkMsbfdWBwnsc0pmu4ftXW4cUFx/zv25T84N4jOyDOvqjCzB1mTuYQjHjzd4gRs6AYu3bIPyfTC8+kl2AKdc2P0pEv4Ll53vmFtxXztxpSuOqNsa1Tvor5SdzAHRT14R6So5+osb8YsR8FO7aammX8z3ez4uRZ+MRSYpGv0OM2LVTk1C9YxtF9EOJ3BSgdhPlOjs0tdU+dBdBFjWgYWOhJKqwxDGJ7SmadjW/W6NjPkVSUunHnEJYHflXYTCfw/sFRPp+0Dz+XdAzyb4lSXNNPL+NYzeTQ6NL5E+zq69EJwiC/0GBaEGChIvyu+5l4uxhYeGPVXhXBsFmQPPMd2Es+LBOupPkh2JwgggeQyB+8jbTDaey+uCNmdy4642ead/zsn9oJ61csNjeFl88zPGAltaNabEaObDpmwL/BkldueZe52C8svIGU8dopdcMU8qqJ4erx/FYHM9n4OvBKpyU72nG25m4y5x15Mgymzi+kjuebNqgsDcq6vnY9+OObGmuVY=
