sudo: false
language: node_js
node_js:
  - "0.12"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
  - npm run deploy
env:
  global:
    secure: GqCnufM43sohy1nQ8a3WachZSUZ4c5pyI5zMyXDcvv0bAJ7Pl22BK21B9iOm01bfMXOSMgHDPNuOht9C9tv1TVr9bntOJ4bcm+fFDk03EV/3+2I6iz71C6hFmYOW3NJU7bGx/hi7V0xjOiMKeSFNBd1L8zmbmAeaJaxpg+plE83BhBV6I3rcds6QKow5UBxVW5gCrgo/O6pdk9z1zPC5rTQ5hDTfCtnJNf1tXzdmi8dN8JS1vbtbdMtwCW+vAa+0qxGXYBkDXgWJCRjBEJrsJ1NHQ32qPG2+9w213c6lVBovon/AbBnotHJqj516U9cIUlM7c4AT779yYLA8auIn1PLtpxJiOrig/suhNDpXrp8lFUjqN2Z0d+QDuz8Ack1h55xUS5Bm7RK7U5NLzJuFiwuipR8AP4JUu8HORIOAYkRGXFz3F63KE0lnbV6/X2hJqK8DU9RMLaMrSNW34akvCqTsOZY+zWNTKq0eFK7TRZ8HNQ77qK8r6mM1KcmMOhsoK0G8tByWstnMjCUoB8030pymRjrsKt7vpcaqmMxjr4BRWzRS9YLqXBPkqQhSH6SRxg5r3k908k+oppAGSm0l0HhWBat4JY8xabPIekAAN0d1zP/np4RwUvyTe2xWfCCaUUUoo/GEVqgRWW5QQXmYYS5Qbp6/aLS0d/GOGdlwr6I=
