export const INPUT_TEXT = 'INPUT_TEXT';
export const CHANGE_FONT = 'CHANGE_FONT';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const CHANGE_BACKGROUND = 'CHANGE_BACKGROUND';
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const INCREMENT_SIZE = 'INCREMENT_SIZE';
export const DECREMENT_SIZE = 'DECREMENT_SIZE';
export const RESET_APPEARANCE = 'RESET_APPEARANCE';
