export const DIR = {
  SITE_ROOT_PATH: '/figleditr',
  SRC: 'src',
  DEST: 'public'
};

export const serve = {
  notify: false,
  startPath: DIR.SITE_ROOT_PATH,
  server: {
    baseDir: './',
    index: `${DIR.DEST}${DIR.SITE_ROOT_PATH}/`,
    routes: {
      [DIR.SITE_ROOT_PATH]: `${DIR.DEST}/`,
      [`${DIR.SITE_ROOT_PATH}/fonts`]: `${DIR.DEST}/fonts`
    }
  }
};

export const scripts = {
  browserifyOpts: {
    entries: [`./${DIR.SRC}/js/index.js`],
    extensions: ['.jsx'],
    transform: [['babelify', {
      presets: ['es2015', 'stage-0', 'react']//,
      // plugins: [
      //   'syntax-object-rest-spread',
      //   'syntax-decorators'
      // ]
    }], 'envify']
  },
  dest: `${DIR.DEST}/js`
};

export const uglify = {
  src: `./${DIR.DEST}/js/index.js`,
  dest: `${DIR.DEST}/js`,
  opts: {
    preserveComments(node, comment) {
      return comment.value.indexOf('This header is generated by licensify') > -1;
    }
  }
};

export const stylus = {
  src: [
    `${DIR.SRC}/**/*.styl`,
    `!${DIR.SRC}/**/_**/*.styl`,
    `!${DIR.SRC}/**/_*.styl`
  ],
  dest: `${DIR.DEST}/css`
};

export const minifyCss = {
  src: `${DIR.DEST}/css/main.css`,
  dest: `${DIR.DEST}/css`
};

export const clean = {
  path: [`${DIR.DEST}`]
};

export const htmlReplace = {
  src: `${DIR.SRC}/index.html`,
  dest: `${DIR.DEST}`
};

export const copy = {
  html: {
    src: `${DIR.SRC}/index.html`,
    dest: `${DIR.DEST}`
  },
  figlet: {
    src: './node_modules/figlet/fonts/**',
    dest: `${DIR.DEST}/fonts`
  }
};
