export const DIR = {
  SITE_ROOT_PATH: '/figleditr',
  SRC: 'src',
  DEST: 'public'
};

export const serve = {
  notify: false,
  startPath: D.SITE_ROOT_PATH,
  server: {
    baseDir: './',
    index: `${D.DEST}${D.SITE_ROOT_PATH}/`,
    routes: {
      [D.SITE_ROOT_PATH]: `${D.DEST}/`,
      [`${D.SITE_ROOT_PATH}/fonts`]: `${D.DEST}/fonts`
    }
  }
};

export const scripts = {
  browserifyOpts: {
    entries: [`./${D.SRC}/js/index.js`],
    extensions: ['.jsx'],
    transform: [['babelify', { stage: 1 }], 'envify']
  },
  dest: `${D.DEST}/js`
};

export const uglify = {
  src: `./${D.DEST}/js/index.js`,
  dest: `${D.DEST}/js`,
  opts: {
    preserveComments(node, comment) {
      return comment.value.indexOf('This header is generated by licensify') > -1;
    }
  }
};

export const stylus = {
  src: [
    `${D.SRC}/**/*.styl`,
    `!${D.SRC}/**/_**/*.styl`,
    `!${D.SRC}/**/_*.styl`
  ],
  dest: `${D.DEST}/css`
};

export const minifyCss = {
  src: `${D.DEST}/css/main.css`,
  dest: `${D.DEST}/css`
};

export const clean = {
  path: [`${D.DEST}`]
};

export const copy = {
  html: {
    src: `${D.SRC}/index.html`,
    dest: `${D.DEST}`
  },
  figlet: {
    src: './node_modules/figlet/fonts/**',
    dest: `${D.DEST}/fonts`
  }
};
